var data = {
	HTML5:{
	name:"HTML5",
	person:[
			{name:"柏**",education:"本科",major:"电子信息工程",company:"上海领健**技术有限公司",money:"13000元",job:"Web前端工程师"},
			{name:"孙*",education:"专科",major:"市场营销",company:"北京享阅**有限公司",money:"11000元",job:"Web前端工程师"},
			{name:"崔*",education:"专科",major:"电子信息工程",company:"北京享阅**有限公司",money:"12000元",job:"Web前端工程师"},
			{name:"宫*",education:"本科",major:"电子信息工程",company:"北京英**科技有限责任公司",money:"12000元",job:"Web前端开发工程师"},
			{name:"何**",education:"专科",major:"市场营销",company:"上海芯*网络科技有限公司",money:"12000元",job:"Web前端开发工程师"},
			{name:"徐**",education:"专科",major:"市场营销",company:"普华**信息技术（上海）有限公司",money:"11000元",job:"Web前端工程师"},
			{name:"柏**",education:"专科",major:"土木工程",company:"上海赢端**科技有限公司",money:"11000元",job:"Web前端工程师"},
			{name:"凌**",education:"专科",major:"物流",company:"北京微众*科技*展有限公司",money:"11000元",job:"Web前端工程师"},
			{name:"雷*",education:"专科",major:"人力资源管理",company:"上海汉得**股份有限公司",money:"11000元",job:"Web前端工程师"},
			{name:"孙*",education:"专科",major:"市场营销",company:"北京享阅**有限公司",money:"11000元",job:"Web前端工程师"},
			{name:"刘*",education:"专科",major:"工商管理",company:"上海领健**技术有限公司",money:"11000元",job:"Web前端工程师"},
			{name:"司**",education:"本科",major:"人力资源管理",company:"北京亲亲**",money:"12000元",job:"Web前端工程师"},
			{name:"闪*",education:"本科",major:"信息与计算科学",company:"福玛**器人科技股份有限公司",money:"10000元",job:"Web前端工程师"},
			{name:"王**",education:"本科",major:"广播电视编导",company:"***有限公司",money:"10000元",job:"Web前端工程师"},
			{name:"祝*",education:"专科",major:"人力资源管理",company:"上海领健**技术有限公司",money:"11000元",job:"Web前端工程师"},
			{name:"曾*",education:"专科",major:"食品科学与工程",company:"腾**科技有限公司",money:"15000元",job:"H5前端工程师"},
			{name:"杨*",education:"本科",major:"市场营销",company:"中企**科技股份有限公司",money:"10000元",job:"JS前端研发工程师"},
			{name:"王*",education:"本科",major:"软件工程",company:"北京**科技有限公司",money:"12000元",job:"Web前端工程师"},
			{name:"满**",education:"本科",major:"信息与计算科学",company:"挖趣**网络科技（北京）有限公司",money:"14000元",job:"Web前端工程师"},
			{name:"张**",education:"本科",major:"船舶与海洋工程",company:"意度**息科技有限公司",money:"15000元",job:"Web前端工程师"},
		]
},
	VRAR游戏:{
	name:"VRAR游戏",
	person:[
	{name:"张**",education:"本科",major:"电子信息工程",company:"上海领健**技术有限公司",money:"13000元",job:"游戏开发"},
	{name:"杨*",education:"本科",major:"市场营销",company:"中企**科技股份有限公司",money:"10000元",job:"Unity3D开发工程师"},
			{name:"王*",education:"本科",major:"软件工程",company:"北京**科技有限公司",money:"12000元",job:"Unity开发工程师"},
			{name:"满**",education:"本科",major:"信息与计算科学",company:"挖趣**网络科技（北京）有限公司",money:"14000元",job:"Unity3D开发工程师"},
			{name:"张**",education:"本科",major:"船舶与海洋工程",company:"意度**息科技有限公司",money:"15000元",job:"Unity3D开发工程师"},
			{name:"柏**",education:"本科",major:"电子信息工程",company:"上海领健**技术有限公司",money:"13000元",job:"AR开发工程师"},
	{name:"杨*",education:"本科",major:"市场营销",company:"中企**科技股份有限公司",money:"10000元",job:"Unity3D开发工程师"},
			{name:"王*",education:"本科",major:"软件工程",company:"北京**科技有限公司",money:"12000元",job:"Unity3D开发工程师"},
			{name:"满**",education:"本科",major:"信息与计算科学",company:"挖趣**网络科技（北京）有限公司",money:"14000元",job:"Unity3D开发工程师"},
			{name:"张**",education:"本科",major:"船舶与海洋工程",company:"意度**息科技有限公司",money:"15000元",job:"Unity游戏开发"},
			{name:"柏**",education:"本科",major:"电子信息工程",company:"上海领健**技术有限公司",money:"13000元",job:"Unity3D开发工程师"},
	{name:"杨*",education:"本科",major:"市场营销",company:"中企**科技股份有限公司",money:"10000元",job:"Unity游戏开发"},
			{name:"王*",education:"本科",major:"软件工程",company:"北京**科技有限公司",money:"12000元",job:"Unity游戏开发"},
			{name:"满**",education:"本科",major:"信息与计算科学",company:"挖趣**网络科技（北京）有限公司",money:"14000元",job:"U3D开发工程师"},
			{name:"张**",education:"本科",major:"船舶与海洋工程",company:"意度**息科技有限公司",money:"15000元",job:"U3D开发工程师"},
			{name:"张**",education:"本科",major:"船舶与海洋工程",company:"意度**息科技有限公司",money:"15000元",job:"Unity3D开发工程师"},
			{name:"柏**",education:"本科",major:"电子信息工程",company:"上海领健**技术有限公司",money:"13000元",job:"AR开发工程师"},
	{name:"杨*",education:"本科",major:"市场营销",company:"中企**科技股份有限公司",money:"10000元",job:"Unity3D开发工程师"},
			{name:"王*",education:"本科",major:"软件工程",company:"北京**科技有限公司",money:"12000元",job:"Unity3D开发工程师"},
	]
	},
	Web安全:{
	name:"Web安全",
	person:[
	{name:"张**",education:"本科",major:"电子信息工程",company:"上海领健**技术有限公司",money:"13000元",job:"Web安全渗透工程师"},
	{name:"杨*",education:"本科",major:"市场营销",company:"中企**科技股份有限公司",money:"10000元",job:"Web安全渗透工程师"},
			{name:"王*",education:"本科",major:"软件工程",company:"北京**科技有限公司",money:"12000元",job:"Web安全渗透工程师"},
			{name:"满**",education:"本科",major:"信息与计算科学",company:"挖趣**网络科技（北京）有限公司",money:"14000元",job:"Web安全渗透工程师"},
			{name:"张**",education:"本科",major:"船舶与海洋工程",company:"意度**息科技有限公司",money:"15000元",job:"安全工程师"},
			{name:"柏**",education:"本科",major:"电子信息工程",company:"上海领健**技术有限公司",money:"13000元",job:"安全工程师"},
	{name:"杨*",education:"本科",major:"市场营销",company:"中企**科技股份有限公司",money:"10000元",job:"安全工程师"},
			{name:"王*",education:"本科",major:"软件工程",company:"北京**科技有限公司",money:"12000元",job:"安全工程师"},
			{name:"满**",education:"本科",major:"信息与计算科学",company:"挖趣**网络科技（北京）有限公司",money:"14000元",job:"渗透测试专员"},
			{name:"张**",education:"本科",major:"船舶与海洋工程",company:"意度**息科技有限公司",money:"15000元",job:"渗透测试专员"},
			{name:"柏**",education:"本科",major:"电子信息工程",company:"上海领健**技术有限公司",money:"13000元",job:"渗透测试专员"},
	{name:"杨*",education:"本科",major:"市场营销",company:"中企**科技股份有限公司",money:"10000元",job:"渗透测试专员"},
			{name:"王*",education:"本科",major:"软件工程",company:"北京**科技有限公司",money:"12000元",job:"渗透测试专员"},
			{name:"满**",education:"本科",major:"信息与计算科学",company:"挖趣**网络科技（北京）有限公司",money:"14000元",job:"渗透测试专员"},
			{name:"张**",education:"本科",major:"船舶与海洋工程",company:"意度**息科技有限公司",money:"15000元",job:"渗透测试专员"},
			{name:"张**",education:"本科",major:"船舶与海洋工程",company:"意度**息科技有限公司",money:"15000元",job:"Web安全渗透工程师"},
			{name:"柏**",education:"本科",major:"电子信息工程",company:"上海领健**技术有限公司",money:"13000元",job:"Web安全渗透工程师"},
	{name:"杨*",education:"本科",major:"市场营销",company:"中企**科技股份有限公司",money:"10000元",job:"Web安全渗透工程师"},
			{name:"王*",education:"本科",major:"软件工程",company:"北京**科技有限公司",money:"12000元",job:"Web安全渗透工程师"},
	]
	},
	Android:{
	name:"Android",
	person:[
	{name:"张**",education:"本科",major:"电子信息工程",company:"上海领健**技术有限公司",money:"13000元",job:"安卓开发工程师"},
	{name:"杨*",education:"本科",major:"市场营销",company:"中企**科技股份有限公司",money:"10000元",job:"安卓开发工程师"},
			{name:"王*",education:"本科",major:"软件工程",company:"北京**科技有限公司",money:"12000元",job:"安卓开发工程师"},
			{name:"满**",education:"本科",major:"信息与计算科学",company:"挖趣**网络科技（北京）有限公司",money:"14000元",job:"安卓开发工程师"},
			{name:"张**",education:"本科",major:"船舶与海洋工程",company:"意度**息科技有限公司",money:"15000元",job:"安卓开发工程师"},
			{name:"柏**",education:"本科",major:"电子信息工程",company:"上海领健**技术有限公司",money:"13000元",job:"安卓开发工程师"},
	{name:"杨*",education:"本科",major:"市场营销",company:"中企**科技股份有限公司",money:"10000元",job:"安卓开发工程师"},
			{name:"王*",education:"本科",major:"软件工程",company:"北京**科技有限公司",money:"12000元",job:"安卓开发工程师"},
			{name:"满**",education:"本科",major:"信息与计算科学",company:"挖趣**网络科技（北京）有限公司",money:"14000元",job:"安卓开发工程师"},
			{name:"张**",education:"本科",major:"船舶与海洋工程",company:"意度**息科技有限公司",money:"15000元",job:"安卓开发工程师"},
			{name:"柏**",education:"本科",major:"电子信息工程",company:"上海领健**技术有限公司",money:"13000元",job:"安卓开发工程师"},
	{name:"杨*",education:"本科",major:"市场营销",company:"中企**科技股份有限公司",money:"10000元",job:"安卓开发工程师"},
			{name:"王*",education:"本科",major:"软件工程",company:"北京**科技有限公司",money:"12000元",job:"安卓开发工程师"},
			{name:"满**",education:"本科",major:"信息与计算科学",company:"挖趣**网络科技（北京）有限公司",money:"14000元",job:"安卓开发工程师"},
			{name:"张**",education:"本科",major:"船舶与海洋工程",company:"意度**息科技有限公司",money:"15000元",job:"安卓开发工程师"},
			{name:"张**",education:"本科",major:"船舶与海洋工程",company:"意度**息科技有限公司",money:"15000元",job:"安卓开发工程师"},
			{name:"柏**",education:"本科",major:"电子信息工程",company:"上海领健**技术有限公司",money:"13000元",job:"安卓开发工程师"},
	{name:"杨*",education:"本科",major:"市场营销",company:"中企**科技股份有限公司",money:"10000元",job:"安卓开发工程师"},
			{name:"王*",education:"本科",major:"软件工程",company:"北京**科技有限公司",money:"12000元",job:"安卓开发工程师"},
	]
	}
	
}




